ALTER TABLE tb_subway_line_station
    ADD COLUMN subway_line_station_code VARCHAR(10) NULL AFTER subway_line_station_id;
/*
지하철 데이터 없는 목록
UPDATE tb_subway_line_station SET subway_line_station_code = '1918' WHERE subway_line_id = 1 AND station_id = 0; -- 전곡 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0409' WHERE subway_line_id = 4 AND station_id = 0; -- 불암산 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2730' WHERE subway_line_id = 7 AND station_id = 0; -- 자양 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2807' WHERE subway_line_id = 8 AND station_id = 0; -- 동구릉 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1919' WHERE subway_line_id = 1 AND station_id = 0; -- 연천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1917' WHERE subway_line_id = 1 AND station_id = 0; -- 청산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2809' WHERE subway_line_id = 8 AND station_id = 0; -- 장자호수공원 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2810' WHERE subway_line_id = 8 AND station_id = 0; -- 암사역사공원 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2806' WHERE subway_line_id = 8 AND station_id = 0; -- 다산 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1268' WHERE subway_line_id = 11 AND station_id = 0; -- 한국항공대 경의중앙선
*/

UPDATE tb_subway_line_station SET subway_line_station_code = '1867' WHERE subway_line_id = 16 AND station_id = 1; -- 청명 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1873' WHERE subway_line_id = 16 AND station_id = 2; -- 고색 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4316' WHERE subway_line_id = 18 AND station_id = 3; -- 성복 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4708' WHERE subway_line_id = 20 AND station_id = 4; -- 솔샘 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '4128' WHERE subway_line_id = 9 AND station_id = 6; -- 삼성중앙 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0213' WHERE subway_line_id = 2 AND station_id = 7; -- 구의 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1701' WHERE subway_line_id = 1 AND station_id = 8; -- 구로 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2551' WHERE subway_line_id = 5 AND station_id = 10; -- 굽은다리 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1210' WHERE subway_line_id = 11 AND station_id = 12; -- 팔당 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2634' WHERE subway_line_id = 6 AND station_id = 13; -- 약수 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0323' WHERE subway_line_id = 3 AND station_id = 13; -- 약수 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3763' WHERE subway_line_id = 7 AND station_id = 14; -- 석남 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1271' WHERE subway_line_id = 11 AND station_id = 15; -- 능곡 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '104C' WHERE subway_line_id = 15 AND station_id = 15; -- 능곡 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '0230' WHERE subway_line_id = 2 AND station_id = 16; -- 신림 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0235' WHERE subway_line_id = 2 AND station_id = 17; -- 문래 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2631' WHERE subway_line_id = 6 AND station_id = 18; -- 이태원 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2543' WHERE subway_line_id = 5 AND station_id = 20; -- 답십리 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2518' WHERE subway_line_id = 5 AND station_id = 21; -- 화곡 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1955' WHERE subway_line_id = 3 AND station_id = 23; -- 마두 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4211' WHERE subway_line_id = 13 AND station_id = 25; -- 운서 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '2517' WHERE subway_line_id = 5 AND station_id = 26; -- 우장산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1803' WHERE subway_line_id = 1 AND station_id = 27; -- 역곡 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4202' WHERE subway_line_id = 13 AND station_id = 28; -- 공덕 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '2627' WHERE subway_line_id = 6 AND station_id = 28; -- 공덕 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1262' WHERE subway_line_id = 11 AND station_id = 28; -- 공덕 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2530' WHERE subway_line_id = 5 AND station_id = 28; -- 공덕 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1722' WHERE subway_line_id = 1 AND station_id = 30; -- 서정리 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2745' WHERE subway_line_id = 7 AND station_id = 32; -- 신풍 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3753' WHERE subway_line_id = 7 AND station_id = 33; -- 까치울 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0424' WHERE subway_line_id = 4 AND station_id = 35; -- 명동 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1915' WHERE subway_line_id = 1 AND station_id = 36; -- 동두천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2512' WHERE subway_line_id = 5 AND station_id = 37; -- 개화산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2733' WHERE subway_line_id = 7 AND station_id = 38; -- 학동 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1317' WHERE subway_line_id = 12 AND station_id = 39; -- 평내호평 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2711' WHERE subway_line_id = 7 AND station_id = 40; -- 장암 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0319' WHERE subway_line_id = 3 AND station_id = 41; -- 종로3가 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2535' WHERE subway_line_id = 5 AND station_id = 41; -- 종로3가 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0153' WHERE subway_line_id = 1 AND station_id = 41; -- 종로3가 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1218' WHERE subway_line_id = 11 AND station_id = 43; -- 원덕 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1326' WHERE subway_line_id = 12 AND station_id = 44; -- 강촌 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1314' WHERE subway_line_id = 12 AND station_id = 45; -- 퇴계원 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '4103' WHERE subway_line_id = 9 AND station_id = 46; -- 공항시장 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2547' WHERE subway_line_id = 5 AND station_id = 47; -- 광나루 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4124' WHERE subway_line_id = 9 AND station_id = 48; -- 사평 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0245' WHERE subway_line_id = 2 AND station_id = 49; -- 신답 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4134' WHERE subway_line_id = 9 AND station_id = 51; -- 송파나루 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2738' WHERE subway_line_id = 7 AND station_id = 53; -- 이수 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4703' WHERE subway_line_id = 20 AND station_id = 54; -- 4·19민주묘지 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '0410' WHERE subway_line_id = 4 AND station_id = 55; -- 상계 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1450' WHERE subway_line_id = 4 AND station_id = 57; -- 선바위 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1269' WHERE subway_line_id = 11 AND station_id = 58; -- 강매 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4705' WHERE subway_line_id = 20 AND station_id = 59; -- 화계 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '1889' WHERE subway_line_id = 16 AND station_id = 60; -- 숭의 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0154' WHERE subway_line_id = 1 AND station_id = 61; -- 종로5가 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0341' WHERE subway_line_id = 3 AND station_id = 63; -- 경찰병원 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1885' WHERE subway_line_id = 16 AND station_id = 64; -- 연수 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0224' WHERE subway_line_id = 2 AND station_id = 65; -- 서초 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0210' WHERE subway_line_id = 2 AND station_id = 66; -- 뚝섬 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1757' WHERE subway_line_id = 4 AND station_id = 67; -- 고잔 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1832' WHERE subway_line_id = 16 AND station_id = 67; -- 고잔 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1329' WHERE subway_line_id = 12 AND station_id = 68; -- 춘천 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1812' WHERE subway_line_id = 1 AND station_id = 69; -- 인천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1891' WHERE subway_line_id = 16 AND station_id = 69; -- 인천 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2516' WHERE subway_line_id = 5 AND station_id = 71; -- 발산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1878' WHERE subway_line_id = 16 AND station_id = 72; -- 달월 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1905' WHERE subway_line_id = 1 AND station_id = 75; -- 회룡 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0216' WHERE subway_line_id = 2 AND station_id = 76; -- 잠실 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2815' WHERE subway_line_id = 8 AND station_id = 76; -- 잠실 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2560' WHERE subway_line_id = 5 AND station_id = 77; -- 거여 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1848' WHERE subway_line_id = 16 AND station_id = 78; -- 압구정로데오 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1951' WHERE subway_line_id = 3 AND station_id = 79; -- 원당 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1914' WHERE subway_line_id = 1 AND station_id = 80; -- 보산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0333' WHERE subway_line_id = 3 AND station_id = 81; -- 매봉 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1705' WHERE subway_line_id = 1 AND station_id = 82; -- 관악 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1800' WHERE subway_line_id = 16 AND station_id = 83; -- 오이도 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1762' WHERE subway_line_id = 4 AND station_id = 83; -- 오이도 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1916' WHERE subway_line_id = 1 AND station_id = 85; -- 소요산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4809' WHERE subway_line_id = 15 AND station_id = 86; -- 시흥시청 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '0229' WHERE subway_line_id = 2 AND station_id = 87; -- 봉천 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0336' WHERE subway_line_id = 3 AND station_id = 88; -- 학여울 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0416' WHERE subway_line_id = 4 AND station_id = 90; -- 미아사거리 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3755' WHERE subway_line_id = 7 AND station_id = 91; -- 춘의 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0324' WHERE subway_line_id = 3 AND station_id = 92; -- 금호 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0310' WHERE subway_line_id = 3 AND station_id = 93; -- 구파발 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0408' WHERE subway_line_id = 4 AND station_id = 94; -- 별내별가람 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1721' WHERE subway_line_id = 1 AND station_id = 95; -- 송탄 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2752' WHERE subway_line_id = 7 AND station_id = 96; -- 온수 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1821' WHERE subway_line_id = 1 AND station_id = 96; -- 온수 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0239' WHERE subway_line_id = 2 AND station_id = 97; -- 홍대입구 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1264' WHERE subway_line_id = 11 AND station_id = 97; -- 홍대입구 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4203' WHERE subway_line_id = 13 AND station_id = 97; -- 홍대입구 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '0414' WHERE subway_line_id = 4 AND station_id = 99; -- 수유 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2724' WHERE subway_line_id = 7 AND station_id = 100; -- 사가정 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1216' WHERE subway_line_id = 11 AND station_id = 101; -- 오빈 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1285' WHERE subway_line_id = 11 AND station_id = 102; -- 임진강 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1275' WHERE subway_line_id = 11 AND station_id = 103; -- 일산 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '108C' WHERE subway_line_id = 15 AND station_id = 103; -- 일산 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1877' WHERE subway_line_id = 16 AND station_id = 104; -- 사리 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4701' WHERE subway_line_id = 20 AND station_id = 105; -- 북한산우이 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '3762' WHERE subway_line_id = 7 AND station_id = 106; -- 산곡 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1024' WHERE subway_line_id = 16 AND station_id = 107; -- 한티 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1007' WHERE subway_line_id = 1 AND station_id = 108; -- 신도림 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0234' WHERE subway_line_id = 2 AND station_id = 108; -- 신도림 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4129' WHERE subway_line_id = 9 AND station_id = 109; -- 봉은사 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0220' WHERE subway_line_id = 2 AND station_id = 110; -- 선릉 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1023' WHERE subway_line_id = 16 AND station_id = 110; -- 선릉 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2817' WHERE subway_line_id = 8 AND station_id = 111; -- 송파 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1320' WHERE subway_line_id = 12 AND station_id = 112; -- 대성리 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1004' WHERE subway_line_id = 1 AND station_id = 113; -- 노량진 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4117' WHERE subway_line_id = 9 AND station_id = 113; -- 노량진 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0152' WHERE subway_line_id = 1 AND station_id = 114; -- 종각 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1207' WHERE subway_line_id = 11 AND station_id = 115; -- 양정 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4136' WHERE subway_line_id = 9 AND station_id = 117; -- 올림픽공원 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2556' WHERE subway_line_id = 5 AND station_id = 117; -- 올림픽공원 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2644' WHERE subway_line_id = 6 AND station_id = 118; -- 돌곶이 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0431' WHERE subway_line_id = 4 AND station_id = 119; -- 동작 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4120' WHERE subway_line_id = 9 AND station_id = 119; -- 동작 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1204' WHERE subway_line_id = 11 AND station_id = 120; -- 양원 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1851' WHERE subway_line_id = 16 AND station_id = 121; -- 가천대 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1855' WHERE subway_line_id = 16 AND station_id = 122; -- 서현 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1954' WHERE subway_line_id = 3 AND station_id = 123; -- 백석 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0243' WHERE subway_line_id = 2 AND station_id = 124; -- 충정로 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2532' WHERE subway_line_id = 5 AND station_id = 124; -- 충정로 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1847' WHERE subway_line_id = 16 AND station_id = 125; -- 서울숲 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4213' WHERE subway_line_id = 13 AND station_id = 126; -- 인천공항1터미널 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '0223' WHERE subway_line_id = 2 AND station_id = 127; -- 교대 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0330' WHERE subway_line_id = 3 AND station_id = 127; -- 교대 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4811' WHERE subway_line_id = 15 AND station_id = 129; -- 달미 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1874' WHERE subway_line_id = 16 AND station_id = 130; -- 오목천 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2534' WHERE subway_line_id = 5 AND station_id = 132; -- 광화문 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2626' WHERE subway_line_id = 6 AND station_id = 133; -- 대흥 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2625' WHERE subway_line_id = 6 AND station_id = 134; -- 광흥창 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2629' WHERE subway_line_id = 6 AND station_id = 135; -- 삼각지 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0428' WHERE subway_line_id = 4 AND station_id = 135; -- 삼각지 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1027' WHERE subway_line_id = 16 AND station_id = 136; -- 개포동 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0225' WHERE subway_line_id = 2 AND station_id = 138; -- 방배 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1870' WHERE subway_line_id = 16 AND station_id = 139; -- 매탄권선 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1754' WHERE subway_line_id = 4 AND station_id = 140; -- 상록수 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1220' WHERE subway_line_id = 11 AND station_id = 141; -- 지평 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1203' WHERE subway_line_id = 11 AND station_id = 143; -- 망우 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1310' WHERE subway_line_id = 12 AND station_id = 143; -- 망우 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '0419' WHERE subway_line_id = 4 AND station_id = 144; -- 한성대입구 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1871' WHERE subway_line_id = 16 AND station_id = 145; -- 수원시청 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4806' WHERE subway_line_id = 15 AND station_id = 146; -- 시흥대야 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '2539' WHERE subway_line_id = 5 AND station_id = 147; -- 신금호 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1503' WHERE subway_line_id = 10 AND station_id = 148; -- 삼동 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '0418' WHERE subway_line_id = 4 AND station_id = 149; -- 성신여대입구 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4711' WHERE subway_line_id = 20 AND station_id = 149; -- 성신여대입구 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '1761' WHERE subway_line_id = 4 AND station_id = 150; -- 정왕 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1836' WHERE subway_line_id = 16 AND station_id = 150; -- 정왕 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2640' WHERE subway_line_id = 6 AND station_id = 151; -- 안암 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2813' WHERE subway_line_id = 8 AND station_id = 152; -- 강동구청 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4118' WHERE subway_line_id = 9 AND station_id = 153; -- 노들 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1876' WHERE subway_line_id = 16 AND station_id = 155; -- 야목 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1006' WHERE subway_line_id = 1 AND station_id = 156; -- 영등포 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1810' WHERE subway_line_id = 1 AND station_id = 157; -- 제물포 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1711' WHERE subway_line_id = 1 AND station_id = 158; -- 성균관대 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '106C' WHERE subway_line_id = 15 AND station_id = 159; -- 백마 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1273' WHERE subway_line_id = 11 AND station_id = 159; -- 백마 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1883' WHERE subway_line_id = 16 AND station_id = 160; -- 남동인더스파크 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1857' WHERE subway_line_id = 16 AND station_id = 161; -- 정자 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4312' WHERE subway_line_id = 18 AND station_id = 161; -- 정자 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4119' WHERE subway_line_id = 9 AND station_id = 163; -- 흑석 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4712' WHERE subway_line_id = 20 AND station_id = 164; -- 보문 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '2639' WHERE subway_line_id = 6 AND station_id = 164; -- 보문 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2633' WHERE subway_line_id = 6 AND station_id = 166; -- 버티고개 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1861' WHERE subway_line_id = 16 AND station_id = 167; -- 보정 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1009' WHERE subway_line_id = 11 AND station_id = 168; -- 서빙고 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1028' WHERE subway_line_id = 16 AND station_id = 169; -- 대모산입구 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1407' WHERE subway_line_id = 1 AND station_id = 170; -- 온양온천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1869' WHERE subway_line_id = 16 AND station_id = 171; -- 망포 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1713' WHERE subway_line_id = 1 AND station_id = 172; -- 수원 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1846' WHERE subway_line_id = 16 AND station_id = 172; -- 수원 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2731' WHERE subway_line_id = 7 AND station_id = 173; -- 청담 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1504' WHERE subway_line_id = 10 AND station_id = 174; -- 경기광주 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '1802' WHERE subway_line_id = 1 AND station_id = 175; -- 오류동 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2624' WHERE subway_line_id = 6 AND station_id = 176; -- 상수 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4217' WHERE subway_line_id = 13 AND station_id = 178; -- 영종 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '0228' WHERE subway_line_id = 2 AND station_id = 180; -- 서울대입구 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1315' WHERE subway_line_id = 12 AND station_id = 181; -- 사릉 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2611' WHERE subway_line_id = 6 AND station_id = 182; -- 응암 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2553' WHERE subway_line_id = 5 AND station_id = 183; -- 고덕 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1845' WHERE subway_line_id = 16 AND station_id = 184; -- 청량리 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0158' WHERE subway_line_id = 1 AND station_id = 184; -- 청량리 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1014' WHERE subway_line_id = 11 AND station_id = 184; -- 청량리 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1306' WHERE subway_line_id = 12 AND station_id = 184; -- 청량리 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '0236' WHERE subway_line_id = 2 AND station_id = 186; -- 영등포구청 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2524' WHERE subway_line_id = 5 AND station_id = 186; -- 영등포구청 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1862' WHERE subway_line_id = 16 AND station_id = 187; -- 죽전 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2515' WHERE subway_line_id = 5 AND station_id = 188; -- 마곡 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1749' WHERE subway_line_id = 1 AND station_id = 189; -- 서동탄 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2749' WHERE subway_line_id = 7 AND station_id = 190; -- 철산 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1212' WHERE subway_line_id = 11 AND station_id = 191; -- 양수 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1865' WHERE subway_line_id = 16 AND station_id = 192; -- 기흥 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0214' WHERE subway_line_id = 2 AND station_id = 193; -- 강변 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4126' WHERE subway_line_id = 9 AND station_id = 194; -- 언주 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1868' WHERE subway_line_id = 16 AND station_id = 195; -- 영통 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1755' WHERE subway_line_id = 4 AND station_id = 196; -- 한대앞 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1830' WHERE subway_line_id = 16 AND station_id = 196; -- 한대앞 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1506' WHERE subway_line_id = 10 AND station_id = 197; -- 곤지암 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '0427' WHERE subway_line_id = 4 AND station_id = 198; -- 숙대입구 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4132' WHERE subway_line_id = 9 AND station_id = 199; -- 석촌고분 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4204' WHERE subway_line_id = 13 AND station_id = 201; -- 디지털미디어시티 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '2619' WHERE subway_line_id = 6 AND station_id = 201; -- 디지털미디어시티 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1266' WHERE subway_line_id = 11 AND station_id = 201; -- 디지털미디어시티 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '107C' WHERE subway_line_id = 15 AND station_id = 202; -- 풍산 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1274' WHERE subway_line_id = 11 AND station_id = 202; -- 풍산 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2621' WHERE subway_line_id = 6 AND station_id = 203; -- 마포구청 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4704' WHERE subway_line_id = 20 AND station_id = 204; -- 가오리 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '0231' WHERE subway_line_id = 2 AND station_id = 205; -- 신대방 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1215' WHERE subway_line_id = 11 AND station_id = 206; -- 아신 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1010' WHERE subway_line_id = 11 AND station_id = 207; -- 한남 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0207' WHERE subway_line_id = 2 AND station_id = 209; -- 상왕십리 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4138' WHERE subway_line_id = 9 AND station_id = 211; -- 중앙보훈병원 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3759' WHERE subway_line_id = 7 AND station_id = 212; -- 삼산체육관 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0332' WHERE subway_line_id = 3 AND station_id = 213; -- 양재 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4308' WHERE subway_line_id = 18 AND station_id = 213; -- 양재 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4133' WHERE subway_line_id = 9 AND station_id = 214; -- 석촌 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2816' WHERE subway_line_id = 8 AND station_id = 214; -- 석촌 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1016' WHERE subway_line_id = 1 AND station_id = 215; -- 외대앞 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2751' WHERE subway_line_id = 7 AND station_id = 216; -- 천왕 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1956' WHERE subway_line_id = 3 AND station_id = 217; -- 정발산 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1816' WHERE subway_line_id = 1 AND station_id = 218; -- 간석 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '102C' WHERE subway_line_id = 16 AND station_id = 219; -- 왕십리 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1013' WHERE subway_line_id = 11 AND station_id = 219; -- 왕십리 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2541' WHERE subway_line_id = 5 AND station_id = 219; -- 왕십리 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0208' WHERE subway_line_id = 2 AND station_id = 219; -- 왕십리 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4107' WHERE subway_line_id = 9 AND station_id = 220; -- 가양 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2563' WHERE subway_line_id = 5 AND station_id = 221; -- 미사 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1759' WHERE subway_line_id = 4 AND station_id = 222; -- 안산 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1834' WHERE subway_line_id = 16 AND station_id = 222; -- 안산 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0338' WHERE subway_line_id = 3 AND station_id = 224; -- 일원 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2729' WHERE subway_line_id = 7 AND station_id = 225; -- 건대입구 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0212' WHERE subway_line_id = 2 AND station_id = 225; -- 건대입구 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0227' WHERE subway_line_id = 2 AND station_id = 226; -- 낙성대 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1882' WHERE subway_line_id = 16 AND station_id = 229; -- 호구포 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1011' WHERE subway_line_id = 11 AND station_id = 230; -- 옥수 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0325' WHERE subway_line_id = 3 AND station_id = 230; -- 옥수 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2735' WHERE subway_line_id = 7 AND station_id = 231; -- 반포 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1853' WHERE subway_line_id = 16 AND station_id = 232; -- 모란 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2827' WHERE subway_line_id = 8 AND station_id = 232; -- 모란 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2523' WHERE subway_line_id = 5 AND station_id = 233; -- 양평 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1217' WHERE subway_line_id = 11 AND station_id = 233; -- 양평 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4319' WHERE subway_line_id = 18 AND station_id = 234; -- 광교 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1408' WHERE subway_line_id = 1 AND station_id = 236; -- 신창 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0411' WHERE subway_line_id = 4 AND station_id = 237; -- 노원 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2715' WHERE subway_line_id = 7 AND station_id = 237; -- 노원 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1252' WHERE subway_line_id = 11 AND station_id = 238; -- 신촌 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0240' WHERE subway_line_id = 2 AND station_id = 238; -- 신촌 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4121' WHERE subway_line_id = 9 AND station_id = 240; -- 구반포 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2618' WHERE subway_line_id = 6 AND station_id = 241; -- 증산 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1012' WHERE subway_line_id = 11 AND station_id = 242; -- 응봉 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1852' WHERE subway_line_id = 16 AND station_id = 243; -- 태평 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0337' WHERE subway_line_id = 3 AND station_id = 244; -- 대청 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1405' WHERE subway_line_id = 1 AND station_id = 245; -- 배방 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2525' WHERE subway_line_id = 5 AND station_id = 246; -- 영등포시장 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4808' WHERE subway_line_id = 15 AND station_id = 247; -- 신현 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '2550' WHERE subway_line_id = 5 AND station_id = 248; -- 길동 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1808' WHERE subway_line_id = 1 AND station_id = 249; -- 동암 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2814' WHERE subway_line_id = 8 AND station_id = 251; -- 몽촌토성 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1854' WHERE subway_line_id = 16 AND station_id = 252; -- 야탑 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1948' WHERE subway_line_id = 3 AND station_id = 253; -- 원흥 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0248' WHERE subway_line_id = 2 AND station_id = 256; -- 양천구청 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3760' WHERE subway_line_id = 7 AND station_id = 257; -- 굴포천 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1319' WHERE subway_line_id = 12 AND station_id = 258; -- 마석 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1703' WHERE subway_line_id = 1 AND station_id = 259; -- 금천구청 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4130' WHERE subway_line_id = 9 AND station_id = 261; -- 종합운동장 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0218' WHERE subway_line_id = 2 AND station_id = 261; -- 종합운동장 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1456' WHERE subway_line_id = 4 AND station_id = 262; -- 평촌 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2632' WHERE subway_line_id = 6 AND station_id = 263; -- 한강진 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0429' WHERE subway_line_id = 4 AND station_id = 266; -- 신용산 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2647' WHERE subway_line_id = 6 AND station_id = 267; -- 화랑대 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1510' WHERE subway_line_id = 10 AND station_id = 268; -- 세종대왕릉 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '0232' WHERE subway_line_id = 2 AND station_id = 269; -- 구로디지털단지 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1270' WHERE subway_line_id = 11 AND station_id = 270; -- 행신 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2528' WHERE subway_line_id = 5 AND station_id = 271; -- 여의나루 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4318' WHERE subway_line_id = 18 AND station_id = 272; -- 광교중앙 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1208' WHERE subway_line_id = 11 AND station_id = 273; -- 덕소 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0432' WHERE subway_line_id = 4 AND station_id = 274; -- 총신대입구 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3757' WHERE subway_line_id = 7 AND station_id = 277; -- 부천시청 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4106' WHERE subway_line_id = 9 AND station_id = 278; -- 양천향교 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4109' WHERE subway_line_id = 9 AND station_id = 279; -- 등촌 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1020' WHERE subway_line_id = 1 AND station_id = 280; -- 월계 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0331' WHERE subway_line_id = 3 AND station_id = 282; -- 남부터미널 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4813' WHERE subway_line_id = 15 AND station_id = 283; -- 초지 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1758' WHERE subway_line_id = 4 AND station_id = 283; -- 초지 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1833' WHERE subway_line_id = 16 AND station_id = 283; -- 초지 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2725' WHERE subway_line_id = 7 AND station_id = 284; -- 용마산 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1910' WHERE subway_line_id = 1 AND station_id = 285; -- 덕계 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2559' WHERE subway_line_id = 5 AND station_id = 287; -- 개롱 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1318' WHERE subway_line_id = 12 AND station_id = 288; -- 천마산 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1872' WHERE subway_line_id = 16 AND station_id = 289; -- 매교 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2522' WHERE subway_line_id = 5 AND station_id = 290; -- 오목교 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1019' WHERE subway_line_id = 1 AND station_id = 291; -- 광운대 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1305' WHERE subway_line_id = 12 AND station_id = 291; -- 광운대 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1909' WHERE subway_line_id = 1 AND station_id = 292; -- 양주 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0328' WHERE subway_line_id = 3 AND station_id = 293; -- 잠원 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1866' WHERE subway_line_id = 16 AND station_id = 294; -- 상갈 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1811' WHERE subway_line_id = 1 AND station_id = 295; -- 동인천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2546' WHERE subway_line_id = 5 AND station_id = 296; -- 아차산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1815' WHERE subway_line_id = 1 AND station_id = 297; -- 부개 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1880' WHERE subway_line_id = 16 AND station_id = 300; -- 소래포구 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1313' WHERE subway_line_id = 12 AND station_id = 301; -- 별내 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2805' WHERE subway_line_id = 8 AND station_id = 301; -- 별내 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4314' WHERE subway_line_id = 18 AND station_id = 302; -- 동천 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2521' WHERE subway_line_id = 5 AND station_id = 303; -- 목동 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0317' WHERE subway_line_id = 3 AND station_id = 304; -- 경복궁 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0405' WHERE subway_line_id = 4 AND station_id = 305; -- 진접 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1809' WHERE subway_line_id = 1 AND station_id = 306; -- 주안 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1801' WHERE subway_line_id = 1 AND station_id = 307; -- 개봉 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1452' WHERE subway_line_id = 4 AND station_id = 308; -- 대공원 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2533' WHERE subway_line_id = 5 AND station_id = 309; -- 서대문 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1282' WHERE subway_line_id = 11 AND station_id = 310; -- 월롱 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4804' WHERE subway_line_id = 15 AND station_id = 311; -- 소사 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1814' WHERE subway_line_id = 1 AND station_id = 311; -- 소사 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2529' WHERE subway_line_id = 5 AND station_id = 312; -- 마포 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2565' WHERE subway_line_id = 5 AND station_id = 313; -- 하남시청 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1719' WHERE subway_line_id = 1 AND station_id = 314; -- 오산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4317' WHERE subway_line_id = 18 AND station_id = 316; -- 상현 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2630' WHERE subway_line_id = 6 AND station_id = 318; -- 녹사평 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2527' WHERE subway_line_id = 5 AND station_id = 319; -- 여의도 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4115' WHERE subway_line_id = 9 AND station_id = 319; -- 여의도 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1875' WHERE subway_line_id = 16 AND station_id = 320; -- 어천 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2828' WHERE subway_line_id = 8 AND station_id = 321; -- 남위례 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1728' WHERE subway_line_id = 1 AND station_id = 323; -- 천안 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2739' WHERE subway_line_id = 7 AND station_id = 324; -- 남성 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0244' WHERE subway_line_id = 2 AND station_id = 325; -- 용답 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2616' WHERE subway_line_id = 6 AND station_id = 326; -- 구산 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0316' WHERE subway_line_id = 3 AND station_id = 328; -- 독립문 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4709' WHERE subway_line_id = 20 AND station_id = 329; -- 북한산보국문 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '0219' WHERE subway_line_id = 2 AND station_id = 330; -- 삼성 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0420' WHERE subway_line_id = 4 AND station_id = 331; -- 혜화 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2643' WHERE subway_line_id = 6 AND station_id = 333; -- 상월곡 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1902' WHERE subway_line_id = 1 AND station_id = 334; -- 도봉 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0322' WHERE subway_line_id = 3 AND station_id = 335; -- 동대입구 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4810' WHERE subway_line_id = 15 AND station_id = 336; -- 시흥능곡 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '4710' WHERE subway_line_id = 20 AND station_id = 337; -- 정릉 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '4815' WHERE subway_line_id = 15 AND station_id = 338; -- 원시 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1822' WHERE subway_line_id = 1 AND station_id = 339; -- 중동 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0415' WHERE subway_line_id = 4 AND station_id = 340; -- 미아 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4812' WHERE subway_line_id = 15 AND station_id = 341; -- 선부 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '0215' WHERE subway_line_id = 2 AND station_id = 342; -- 잠실나루 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1017' WHERE subway_line_id = 1 AND station_id = 343; -- 신이문 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4208' WHERE subway_line_id = 13 AND station_id = 344; -- 계양 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '1726' WHERE subway_line_id = 1 AND station_id = 345; -- 직산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2743' WHERE subway_line_id = 7 AND station_id = 346; -- 신대방삼거리 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1205' WHERE subway_line_id = 11 AND station_id = 347; -- 구리 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2808' WHERE subway_line_id = 8 AND station_id = 347; -- 구리 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1008' WHERE subway_line_id = 11 AND station_id = 348; -- 이촌 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0430' WHERE subway_line_id = 4 AND station_id = 348; -- 이촌 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1280' WHERE subway_line_id = 11 AND station_id = 349; -- 금촌 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2544' WHERE subway_line_id = 5 AND station_id = 350; -- 장한평 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4101' WHERE subway_line_id = 9 AND station_id = 351; -- 개화 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0250' WHERE subway_line_id = 2 AND station_id = 352; -- 용두 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0209' WHERE subway_line_id = 2 AND station_id = 353; -- 한양대 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0201' WHERE subway_line_id = 2 AND station_id = 354; -- 시청 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0151' WHERE subway_line_id = 1 AND station_id = 354; -- 시청 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1717' WHERE subway_line_id = 1 AND station_id = 355; -- 세마 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1276' WHERE subway_line_id = 11 AND station_id = 356; -- 탄현 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2728' WHERE subway_line_id = 7 AND station_id = 357; -- 어린이대공원 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1324' WHERE subway_line_id = 12 AND station_id = 358; -- 굴봉산 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1277' WHERE subway_line_id = 11 AND station_id = 359; -- 야당 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0329' WHERE subway_line_id = 3 AND station_id = 360; -- 고속터미널 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4123' WHERE subway_line_id = 9 AND station_id = 360; -- 고속터미널 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2736' WHERE subway_line_id = 7 AND station_id = 360; -- 고속터미널 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2641' WHERE subway_line_id = 6 AND station_id = 362; -- 고려대 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3754' WHERE subway_line_id = 7 AND station_id = 363; -- 부천종합운동장 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1982' WHERE subway_line_id = 15 AND station_id = 363; -- 부천종합운동장 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '4122' WHERE subway_line_id = 9 AND station_id = 364; -- 신반포 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1328' WHERE subway_line_id = 12 AND station_id = 365; -- 남춘천 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '0417' WHERE subway_line_id = 4 AND station_id = 366; -- 길음 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2742' WHERE subway_line_id = 7 AND station_id = 367; -- 장승배기 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2548' WHERE subway_line_id = 5 AND station_id = 368; -- 천호 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2812' WHERE subway_line_id = 8 AND station_id = 368; -- 천호 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1213' WHERE subway_line_id = 11 AND station_id = 369; -- 신원 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2819' WHERE subway_line_id = 8 AND station_id = 370; -- 문정 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1327' WHERE subway_line_id = 12 AND station_id = 371; -- 김유정 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2721' WHERE subway_line_id = 7 AND station_id = 373; -- 중화 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2564' WHERE subway_line_id = 5 AND station_id = 375; -- 하남풍산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1716' WHERE subway_line_id = 1 AND station_id = 376; -- 병점 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1022' WHERE subway_line_id = 1 AND station_id = 377; -- 창동 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0412' WHERE subway_line_id = 4 AND station_id = 377; -- 창동 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1712' WHERE subway_line_id = 1 AND station_id = 378; -- 화서 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1906' WHERE subway_line_id = 1 AND station_id = 379; -- 의정부 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4209' WHERE subway_line_id = 13 AND station_id = 380; -- 검암 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '1886' WHERE subway_line_id = 16 AND station_id = 381; -- 송도 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1458' WHERE subway_line_id = 4 AND station_id = 382; -- 금정 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1708' WHERE subway_line_id = 1 AND station_id = 382; -- 금정 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1720' WHERE subway_line_id = 1 AND station_id = 383; -- 진위 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1312' WHERE subway_line_id = 12 AND station_id = 384; -- 갈매 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1884' WHERE subway_line_id = 16 AND station_id = 386; -- 원인재 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1952' WHERE subway_line_id = 3 AND station_id = 387; -- 화정 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4110' WHERE subway_line_id = 9 AND station_id = 388; -- 염창 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2642' WHERE subway_line_id = 6 AND station_id = 390; -- 월곡 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4306' WHERE subway_line_id = 18 AND station_id = 391; -- 신논현 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4125' WHERE subway_line_id = 9 AND station_id = 391; -- 신논현 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0340' WHERE subway_line_id = 3 AND station_id = 392; -- 가락시장 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2818' WHERE subway_line_id = 8 AND station_id = 392; -- 가락시장 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2552' WHERE subway_line_id = 5 AND station_id = 393; -- 명일 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1272' WHERE subway_line_id = 11 AND station_id = 394; -- 곡산 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '105C' WHERE subway_line_id = 15 AND station_id = 394; -- 곡산 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1453' WHERE subway_line_id = 4 AND station_id = 395; -- 과천 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1026' WHERE subway_line_id = 16 AND station_id = 396; -- 구룡 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0157' WHERE subway_line_id = 1 AND station_id = 397; -- 제기동 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0246' WHERE subway_line_id = 2 AND station_id = 398; -- 신설동 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4713' WHERE subway_line_id = 20 AND station_id = 398; -- 신설동 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '0156' WHERE subway_line_id = 1 AND station_id = 398; -- 신설동 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2540' WHERE subway_line_id = 5 AND station_id = 399; -- 행당 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2561' WHERE subway_line_id = 5 AND station_id = 400; -- 마천 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2526' WHERE subway_line_id = 5 AND station_id = 401; -- 신길 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1032' WHERE subway_line_id = 1 AND station_id = 401; -- 신길 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1404' WHERE subway_line_id = 1 AND station_id = 402; -- 탕정 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0226' WHERE subway_line_id = 2 AND station_id = 403; -- 사당 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0433' WHERE subway_line_id = 4 AND station_id = 403; -- 사당 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1505' WHERE subway_line_id = 10 AND station_id = 404; -- 초월 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '1805' WHERE subway_line_id = 1 AND station_id = 405; -- 송내 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0242' WHERE subway_line_id = 2 AND station_id = 406; -- 아현 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2622' WHERE subway_line_id = 6 AND station_id = 407; -- 망원 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0155' WHERE subway_line_id = 1 AND station_id = 408; -- 동대문 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0421' WHERE subway_line_id = 4 AND station_id = 408; -- 동대문 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1881' WHERE subway_line_id = 16 AND station_id = 409; -- 인천논현 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1403' WHERE subway_line_id = 1 AND station_id = 410; -- 아산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1321' WHERE subway_line_id = 12 AND station_id = 411; -- 청평 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1005' WHERE subway_line_id = 1 AND station_id = 412; -- 대방 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4310' WHERE subway_line_id = 18 AND station_id = 413; -- 청계산입구 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2712' WHERE subway_line_id = 7 AND station_id = 414; -- 도봉산 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1903' WHERE subway_line_id = 1 AND station_id = 414; -- 도봉산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1760' WHERE subway_line_id = 4 AND station_id = 415; -- 신길온천 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1835' WHERE subway_line_id = 16 AND station_id = 415; -- 신길온천 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2734' WHERE subway_line_id = 7 AND station_id = 416; -- 논현 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4305' WHERE subway_line_id = 18 AND station_id = 416; -- 논현 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '3758' WHERE subway_line_id = 7 AND station_id = 418; -- 상동 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4212' WHERE subway_line_id = 13 AND station_id = 420; -- 공항화물청사 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '1859' WHERE subway_line_id = 16 AND station_id = 421; -- 오리 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2750' WHERE subway_line_id = 7 AND station_id = 422; -- 광명사거리 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1309' WHERE subway_line_id = 12 AND station_id = 423; -- 상봉 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2722' WHERE subway_line_id = 7 AND station_id = 423; -- 상봉 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1202' WHERE subway_line_id = 11 AND station_id = 423; -- 상봉 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2538' WHERE subway_line_id = 5 AND station_id = 425; -- 청구 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2635' WHERE subway_line_id = 6 AND station_id = 425; -- 청구 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1286' WHERE subway_line_id = 11 AND station_id = 427; -- 운천 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2811' WHERE subway_line_id = 8 AND station_id = 429; -- 암사 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2519' WHERE subway_line_id = 5 AND station_id = 430; -- 까치산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0200' WHERE subway_line_id = 2 AND station_id = 430; -- 까치산 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2511' WHERE subway_line_id = 5 AND station_id = 431; -- 방화 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2514' WHERE subway_line_id = 5 AND station_id = 432; -- 송정 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4131' WHERE subway_line_id = 9 AND station_id = 433; -- 삼전 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1729' WHERE subway_line_id = 1 AND station_id = 434; -- 당정 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0314' WHERE subway_line_id = 3 AND station_id = 436; -- 홍제 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2740' WHERE subway_line_id = 7 AND station_id = 437; -- 숭실대입구 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1823' WHERE subway_line_id = 1 AND station_id = 438; -- 도화 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1511' WHERE subway_line_id = 10 AND station_id = 439; -- 여주 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '0241' WHERE subway_line_id = 2 AND station_id = 440; -- 이대 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4113' WHERE subway_line_id = 9 AND station_id = 441; -- 당산 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0237' WHERE subway_line_id = 2 AND station_id = 441; -- 당산 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4137' WHERE subway_line_id = 9 AND station_id = 442; -- 둔촌오륜 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1002' WHERE subway_line_id = 1 AND station_id = 443; -- 남영 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1704' WHERE subway_line_id = 1 AND station_id = 444; -- 석수 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1219' WHERE subway_line_id = 11 AND station_id = 445; -- 용문 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1981' WHERE subway_line_id = 15 AND station_id = 446; -- 원종 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '0159' WHERE subway_line_id = 1 AND station_id = 447; -- 동묘앞 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2637' WHERE subway_line_id = 6 AND station_id = 447; -- 동묘앞 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2737' WHERE subway_line_id = 7 AND station_id = 448; -- 내방 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2824' WHERE subway_line_id = 8 AND station_id = 449; -- 단대오거리 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1211' WHERE subway_line_id = 11 AND station_id = 450; -- 운길산 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0313' WHERE subway_line_id = 3 AND station_id = 451; -- 녹번 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1807' WHERE subway_line_id = 1 AND station_id = 452; -- 백운 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0434' WHERE subway_line_id = 4 AND station_id = 454; -- 남태령 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1863' WHERE subway_line_id = 16 AND station_id = 456; -- 구성 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1508' WHERE subway_line_id = 10 AND station_id = 457; -- 이천 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '2825' WHERE subway_line_id = 8 AND station_id = 459; -- 신흥 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1813' WHERE subway_line_id = 1 AND station_id = 460; -- 구일 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1752' WHERE subway_line_id = 4 AND station_id = 461; -- 대야미 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2558' WHERE subway_line_id = 5 AND station_id = 463; -- 오금 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0342' WHERE subway_line_id = 3 AND station_id = 463; -- 오금 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1267' WHERE subway_line_id = 11 AND station_id = 464; -- 수색 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1750' WHERE subway_line_id = 1 AND station_id = 465; -- 광명 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4805' WHERE subway_line_id = 15 AND station_id = 467; -- 소새울 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '2719' WHERE subway_line_id = 7 AND station_id = 469; -- 태릉입구 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2646' WHERE subway_line_id = 6 AND station_id = 469; -- 태릉입구 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0217' WHERE subway_line_id = 2 AND station_id = 470; -- 잠실새내 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2718' WHERE subway_line_id = 7 AND station_id = 471; -- 공릉 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1279' WHERE subway_line_id = 11 AND station_id = 472; -- 금릉 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2726' WHERE subway_line_id = 7 AND station_id = 473; -- 중곡 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1715' WHERE subway_line_id = 1 AND station_id = 474; -- 세류 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2716' WHERE subway_line_id = 7 AND station_id = 475; -- 중계 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1003' WHERE subway_line_id = 1 AND station_id = 476; -- 용산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '100C' WHERE subway_line_id = 11 AND station_id = 476; -- 용산 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1957' WHERE subway_line_id = 3 AND station_id = 477; -- 주엽 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0315' WHERE subway_line_id = 3 AND station_id = 478; -- 무악재 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2823' WHERE subway_line_id = 8 AND station_id = 479; -- 남한산성입구 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1263' WHERE subway_line_id = 11 AND station_id = 480; -- 서강대 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1913' WHERE subway_line_id = 1 AND station_id = 481; -- 동두천중앙 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1908' WHERE subway_line_id = 1 AND station_id = 482; -- 녹양 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1723' WHERE subway_line_id = 1 AND station_id = 483; -- 평택지제 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2562' WHERE subway_line_id = 5 AND station_id = 484; -- 강일 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1718' WHERE subway_line_id = 1 AND station_id = 485; -- 오산대 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1402' WHERE subway_line_id = 1 AND station_id = 486; -- 쌍용 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4104' WHERE subway_line_id = 9 AND station_id = 487; -- 신방화 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2614' WHERE subway_line_id = 6 AND station_id = 488; -- 독바위 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1804' WHERE subway_line_id = 1 AND station_id = 489; -- 부천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2826' WHERE subway_line_id = 8 AND station_id = 490; -- 수진 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2720' WHERE subway_line_id = 7 AND station_id = 492; -- 먹골 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1454' WHERE subway_line_id = 4 AND station_id = 493; -- 정부과천청사 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4315' WHERE subway_line_id = 18 AND station_id = 494; -- 수지구청 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0249' WHERE subway_line_id = 2 AND station_id = 495; -- 신정네거리 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1727' WHERE subway_line_id = 1 AND station_id = 496; -- 두정 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0312' WHERE subway_line_id = 3 AND station_id = 497; -- 불광 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2613' WHERE subway_line_id = 6 AND station_id = 497; -- 불광 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1316' WHERE subway_line_id = 12 AND station_id = 498; -- 금곡 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '0425' WHERE subway_line_id = 4 AND station_id = 499; -- 회현 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1455' WHERE subway_line_id = 4 AND station_id = 500; -- 인덕원 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4112' WHERE subway_line_id = 9 AND station_id = 501; -- 선유도 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1901' WHERE subway_line_id = 1 AND station_id = 502; -- 방학 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0422' WHERE subway_line_id = 4 AND station_id = 503; -- 동대문역사문화공원 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0205' WHERE subway_line_id = 2 AND station_id = 503; -- 동대문역사문화공원 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2537' WHERE subway_line_id = 5 AND station_id = 503; -- 동대문역사문화공원 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1890' WHERE subway_line_id = 16 AND station_id = 505; -- 신포 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1209' WHERE subway_line_id = 11 AND station_id = 506; -- 도심 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2713' WHERE subway_line_id = 7 AND station_id = 507; -- 수락산 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1509' WHERE subway_line_id = 10 AND station_id = 510; -- 부발 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '1950' WHERE subway_line_id = 3 AND station_id = 512; -- 삼송 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2612' WHERE subway_line_id = 6 AND station_id = 514; -- 역촌 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0311' WHERE subway_line_id = 3 AND station_id = 516; -- 연신내 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2615' WHERE subway_line_id = 6 AND station_id = 516; -- 연신내 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4706' WHERE subway_line_id = 20 AND station_id = 517; -- 삼양 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '1707' WHERE subway_line_id = 1 AND station_id = 519; -- 명학 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2554' WHERE subway_line_id = 5 AND station_id = 520; -- 상일동 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4206' WHERE subway_line_id = 13 AND station_id = 521; -- 마곡나루 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '4105' WHERE subway_line_id = 9 AND station_id = 521; -- 마곡나루 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0413' WHERE subway_line_id = 4 AND station_id = 522; -- 쌍문 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2645' WHERE subway_line_id = 6 AND station_id = 523; -- 석계 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1018' WHERE subway_line_id = 1 AND station_id = 523; -- 석계 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0335' WHERE subway_line_id = 3 AND station_id = 524; -- 대치 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2555' WHERE subway_line_id = 5 AND station_id = 525; -- 둔촌동 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1401' WHERE subway_line_id = 1 AND station_id = 526; -- 봉명 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1879' WHERE subway_line_id = 16 AND station_id = 527; -- 월곶 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1702' WHERE subway_line_id = 1 AND station_id = 529; -- 가산디지털단지 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2748' WHERE subway_line_id = 7 AND station_id = 529; -- 가산디지털단지 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1856' WHERE subway_line_id = 16 AND station_id = 532; -- 수내 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0326' WHERE subway_line_id = 3 AND station_id = 533; -- 압구정 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1311' WHERE subway_line_id = 12 AND station_id = 534; -- 신내 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2649' WHERE subway_line_id = 6 AND station_id = 534; -- 신내 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1753' WHERE subway_line_id = 4 AND station_id = 535; -- 반월 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1206' WHERE subway_line_id = 11 AND station_id = 536; -- 도농 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2520' WHERE subway_line_id = 5 AND station_id = 538; -- 신정 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2542' WHERE subway_line_id = 5 AND station_id = 539; -- 마장 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0334' WHERE subway_line_id = 3 AND station_id = 540; -- 도곡 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1025' WHERE subway_line_id = 16 AND station_id = 540; -- 도곡 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1457' WHERE subway_line_id = 4 AND station_id = 541; -- 범계 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4135' WHERE subway_line_id = 9 AND station_id = 542; -- 한성백제 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4707' WHERE subway_line_id = 20 AND station_id = 543; -- 삼양사거리 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '1911' WHERE subway_line_id = 1 AND station_id = 545; -- 덕정 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2531' WHERE subway_line_id = 5 AND station_id = 546; -- 애오개 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4114' WHERE subway_line_id = 9 AND station_id = 547; -- 국회의사당 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1864' WHERE subway_line_id = 16 AND station_id = 548; -- 신갈 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1284' WHERE subway_line_id = 11 AND station_id = 549; -- 문산 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0247' WHERE subway_line_id = 2 AND station_id = 550; -- 도림천 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1502' WHERE subway_line_id = 10 AND station_id = 551; -- 이매 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '1860' WHERE subway_line_id = 16 AND station_id = 551; -- 이매 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0211' WHERE subway_line_id = 2 AND station_id = 552; -- 성수 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2717' WHERE subway_line_id = 7 AND station_id = 553; -- 하계 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1015' WHERE subway_line_id = 1 AND station_id = 555; -- 회기 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '101C' WHERE subway_line_id = 11 AND station_id = 555; -- 회기 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1307' WHERE subway_line_id = 12 AND station_id = 555; -- 회기 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '0318' WHERE subway_line_id = 3 AND station_id = 556; -- 안국 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4307' WHERE subway_line_id = 18 AND station_id = 557; -- 강남 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0222' WHERE subway_line_id = 2 AND station_id = 557; -- 강남 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4108' WHERE subway_line_id = 9 AND station_id = 558; -- 증미 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2727' WHERE subway_line_id = 7 AND station_id = 559; -- 군자 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2545' WHERE subway_line_id = 5 AND station_id = 559; -- 군자 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0233' WHERE subway_line_id = 2 AND station_id = 560; -- 대림 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2746' WHERE subway_line_id = 7 AND station_id = 560; -- 대림 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1958' WHERE subway_line_id = 3 AND station_id = 561; -- 대화 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '3756' WHERE subway_line_id = 7 AND station_id = 562; -- 신중동 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1278' WHERE subway_line_id = 11 AND station_id = 563; -- 운정 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4309' WHERE subway_line_id = 18 AND station_id = 565; -- 양재시민의숲 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2617' WHERE subway_line_id = 6 AND station_id = 566; -- 새절 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4210' WHERE subway_line_id = 13 AND station_id = 567; -- 청라국제도시 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '1706' WHERE subway_line_id = 1 AND station_id = 568; -- 안양 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0300' WHERE subway_line_id = 11 AND station_id = 569; -- 대곡 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1953' WHERE subway_line_id = 3 AND station_id = 569; -- 대곡 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '103C' WHERE subway_line_id = 15 AND station_id = 569; -- 대곡 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1725' WHERE subway_line_id = 1 AND station_id = 570; -- 성환 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0238' WHERE subway_line_id = 2 AND station_id = 571; -- 합정 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2623' WHERE subway_line_id = 6 AND station_id = 571; -- 합정 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0309' WHERE subway_line_id = 3 AND station_id = 572; -- 지축 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4215' WHERE subway_line_id = 13 AND station_id = 573; -- 인천공항2터미널 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '1907' WHERE subway_line_id = 1 AND station_id = 575; -- 가능 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0206' WHERE subway_line_id = 2 AND station_id = 576; -- 신당 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2636' WHERE subway_line_id = 6 AND station_id = 576; -- 신당 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0203' WHERE subway_line_id = 2 AND station_id = 577; -- 을지로3가 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0320' WHERE subway_line_id = 3 AND station_id = 577; -- 을지로3가 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1751' WHERE subway_line_id = 4 AND station_id = 578; -- 산본 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1817' WHERE subway_line_id = 1 AND station_id = 579; -- 도원 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1507' WHERE subway_line_id = 10 AND station_id = 581; -- 신둔도예촌 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '1709' WHERE subway_line_id = 1 AND station_id = 583; -- 군포 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0221' WHERE subway_line_id = 2 AND station_id = 584; -- 역삼 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2741' WHERE subway_line_id = 7 AND station_id = 585; -- 상도 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2744' WHERE subway_line_id = 7 AND station_id = 586; -- 보라매 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1201' WHERE subway_line_id = 11 AND station_id = 588; -- 중랑 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1308' WHERE subway_line_id = 12 AND station_id = 588; -- 중랑 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1858' WHERE subway_line_id = 16 AND station_id = 589; -- 미금 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '4313' WHERE subway_line_id = 18 AND station_id = 589; -- 미금 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1451' WHERE subway_line_id = 4 AND station_id = 590; -- 경마공원 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4702' WHERE subway_line_id = 20 AND station_id = 591; -- 솔밭공원 우이신설경전철
UPDATE tb_subway_line_station SET subway_line_station_code = '3761' WHERE subway_line_id = 7 AND station_id = 592; -- 부평구청 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2820' WHERE subway_line_id = 8 AND station_id = 593; -- 장지 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1323' WHERE subway_line_id = 12 AND station_id = 594; -- 가평 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1322' WHERE subway_line_id = 12 AND station_id = 595; -- 상천 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '2566' WHERE subway_line_id = 5 AND station_id = 596; -- 하남검단산 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2747' WHERE subway_line_id = 7 AND station_id = 597; -- 남구로 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1265' WHERE subway_line_id = 11 AND station_id = 598; -- 가좌 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '1849' WHERE subway_line_id = 16 AND station_id = 599; -- 강남구청 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '2732' WHERE subway_line_id = 7 AND station_id = 599; -- 강남구청 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2648' WHERE subway_line_id = 6 AND station_id = 600; -- 봉화산 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2723' WHERE subway_line_id = 7 AND station_id = 601; -- 면목 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1214' WHERE subway_line_id = 11 AND station_id = 602; -- 국수 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '4807' WHERE subway_line_id = 15 AND station_id = 603; -- 신천 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '1806' WHERE subway_line_id = 1 AND station_id = 604; -- 부평 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0202' WHERE subway_line_id = 2 AND station_id = 605; -- 을지로입구 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2638' WHERE subway_line_id = 6 AND station_id = 606; -- 창신 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1714' WHERE subway_line_id = 1 AND station_id = 607; -- 독산 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4311' WHERE subway_line_id = 18 AND station_id = 608; -- 판교 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1501' WHERE subway_line_id = 10 AND station_id = 608; -- 판교 경강선
UPDATE tb_subway_line_station SET subway_line_station_code = '2821' WHERE subway_line_id = 8 AND station_id = 609; -- 복정 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1031' WHERE subway_line_id = 16 AND station_id = 609; -- 복정 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1763' WHERE subway_line_id = 4 AND station_id = 610; -- 수리산 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1912' WHERE subway_line_id = 1 AND station_id = 611; -- 지행 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1021' WHERE subway_line_id = 1 AND station_id = 612; -- 녹천 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4814' WHERE subway_line_id = 15 AND station_id = 613; -- 시우 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '0423' WHERE subway_line_id = 4 AND station_id = 615; -- 충무로 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0321' WHERE subway_line_id = 3 AND station_id = 615; -- 충무로 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2714' WHERE subway_line_id = 7 AND station_id = 616; -- 마들 7호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1710' WHERE subway_line_id = 1 AND station_id = 617; -- 의왕 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4127' WHERE subway_line_id = 9 AND station_id = 618; -- 선정릉 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1850' WHERE subway_line_id = 16 AND station_id = 618; -- 선정릉 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1283' WHERE subway_line_id = 11 AND station_id = 619; -- 파주 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2557' WHERE subway_line_id = 5 AND station_id = 621; -- 방이 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1030' WHERE subway_line_id = 16 AND station_id = 622; -- 수서 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0339' WHERE subway_line_id = 3 AND station_id = 622; -- 수서 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1980' WHERE subway_line_id = 15 AND station_id = 623; -- 김포공항 서해선
UPDATE tb_subway_line_station SET subway_line_station_code = '4102' WHERE subway_line_id = 9 AND station_id = 623; -- 김포공항 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4207' WHERE subway_line_id = 13 AND station_id = 623; -- 김포공항 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '2513' WHERE subway_line_id = 5 AND station_id = 623; -- 김포공항 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1261' WHERE subway_line_id = 11 AND station_id = 624; -- 효창공원앞 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '2628' WHERE subway_line_id = 6 AND station_id = 624; -- 효창공원앞 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4116' WHERE subway_line_id = 9 AND station_id = 625; -- 샛강 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0204' WHERE subway_line_id = 2 AND station_id = 626; -- 을지로4가 2호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2536' WHERE subway_line_id = 5 AND station_id = 626; -- 을지로4가 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1888' WHERE subway_line_id = 16 AND station_id = 628; -- 인하대 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1831' WHERE subway_line_id = 16 AND station_id = 629; -- 중앙 수인분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '1756' WHERE subway_line_id = 4 AND station_id = 629; -- 중앙 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4201' WHERE subway_line_id = 13 AND station_id = 630; -- 서울역 공항철도
UPDATE tb_subway_line_station SET subway_line_station_code = '1251' WHERE subway_line_id = 11 AND station_id = 630; -- 서울역 경의중앙선
UPDATE tb_subway_line_station SET subway_line_station_code = '0426' WHERE subway_line_id = 4 AND station_id = 630; -- 서울역 4호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0150' WHERE subway_line_id = 1 AND station_id = 630; -- 서울역 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4111' WHERE subway_line_id = 9 AND station_id = 631; -- 신목동 9호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1325' WHERE subway_line_id = 12 AND station_id = 632; -- 백양리 경춘선
UPDATE tb_subway_line_station SET subway_line_station_code = '1904' WHERE subway_line_id = 1 AND station_id = 633; -- 망월사 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2620' WHERE subway_line_id = 6 AND station_id = 634; -- 월드컵경기장 6호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2822' WHERE subway_line_id = 8 AND station_id = 635; -- 산성 8호선
UPDATE tb_subway_line_station SET subway_line_station_code = '1724' WHERE subway_line_id = 1 AND station_id = 636; -- 평택 1호선
UPDATE tb_subway_line_station SET subway_line_station_code = '4304' WHERE subway_line_id = 18 AND station_id = 637; -- 신사 신분당선
UPDATE tb_subway_line_station SET subway_line_station_code = '0327' WHERE subway_line_id = 3 AND station_id = 637; -- 신사 3호선
UPDATE tb_subway_line_station SET subway_line_station_code = '2549' WHERE subway_line_id = 5 AND station_id = 639; -- 강동 5호선
UPDATE tb_subway_line_station SET subway_line_station_code = '0406' WHERE subway_line_id = 4 AND station_id = 640; -- 오남 4호선