version: '3.8'

services:
  spring-app:
    image: ${ECR_REPOSITORY_URI}/app:latest
    container_name: batch-dev-container
    ports:
      - "8080:8080"
    volumes:
      - ahachul-data:/app/ahachul_data/datas
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - cron-container

  cron-app:
    image: ${ECR_REPOSITORY_URI}/cron:latest
    container_name: batch-dev-cron-container
    volumes:
      - ahachul-data:/app/ahachul_data/datas

volumes:
  ahachul-data:
