name: PR Test

on:
  pull_request:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Parse combined secrets
        id: parse_secrets
        run: |
          echo "Extracting secrets..."
          echo '${{ secrets.DEV_API_META_DATA }}' | jq -r 'to_entries | .[] | "echo \(.key)=\(.value) >> $GITHUB_ENV"' | bash

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN_GITHUB }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile Test Kotlin
        run: ./gradlew compileTestKotlin

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: application/build/test-results/**/*.xml
